name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']


# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # We generate static HTML, JS, CSS so we need write access to the repo
      pull-requests: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Fix for "Cannot find module @rollup/rollup-linux-x64-gnu" error
      - name: Clean npm cache
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install --no-optional

      - name: Build project
        run: npm run build
        env:
          VITE_FIGMA_TOKEN: ${{ secrets.VITE_FIGMA_TOKEN }}
          VITE_FIGMA_FILE_NAME: ${{ secrets.VITE_FIGMA_FILE_NAME }}
          VITE_FIGMA_TOKEN_NEURON: ${{ secrets.VITE_FIGMA_TOKEN_NEURON }}
          VITE_FIGMA_FILE_NAME_NEURON: ${{ secrets.VITE_FIGMA_FILE_NAME_NEURON }}
          VITE_FIGMA_FILE_NAME_NEURON_THEME: ${{ secrets.VITE_FIGMA_FILE_NAME_NEURON_THEME }}
          VITE_FIGMA_TOKEN_HMH: ${{ secrets.VITE_FIGMA_TOKEN_HMH }}
          VITE_FIGMA_FILE_NAME_HMH: ${{ secrets.VITE_FIGMA_FILE_NAME_HMH }}
          VITE_FIGMA_FILE_NAME_HMH_THEME: ${{ secrets.VITE_FIGMA_FILE_NAME_HMH_THEME }}
          BASE_URL: /Visual-Editor/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
